# Python variables and Data Types

Create a variable with name x and a value of 10. Execute.

Tell the computer to show you the value of that variable without utilizing the print() function, similar to what you would do in Jupyter.

In [11]:
x = 10

In [12]:
print(x)

10


Create a variable with name x and a value of 10. Execute

In [13]:
x=10
x

10

On the same line, create four new variables: a, b, c, and d, that are equal to 10, 20, 30, and 40, respectively.

In [14]:
a,b,c,d = (10,20,30,40)

On the same line, create four new variables: a, b, c, and d, that are equal to 10, 20, 30, and 40, respectively.
Tell the computer to show you the value corresponding to the variable b.
Do the same for d.

In [15]:
a,b,c,d= (10,20,30,40)

40

In [16]:
b

20

In [17]:
d

40

Create a variable a equal to "True".
Check its type.

In [18]:
x1= True

In [19]:
type(x1)

bool

Create a variable b equal to 99.
Check its type.

In [20]:
b=99

In [21]:
type(b)

int

Check the type of the value 0.99.

In [22]:
type(0.99)

float

Create a variable b equal to 99.
Turn b into a float.
Consider using the print() function as a tool to 
help you solve this exercise.

In [24]:
b=99
print(float(b))

99.0


In [25]:
int(0.99)

0

Assign the value of 100 to the variable m.

With the help of the variable m, write one line of code where the output after execution would be 100 days.

Hint: You could provide four answers to this question!

In [27]:
m=100
print(str(m)+' Days ')

100 Days 


Produce an output equal to It's cool, isn't it? .

In [29]:
print('It\'s cool, isn\'t it? .')

It's cool, isn't it? .


In [30]:
 'Don\'t be shy'

"Don't be shy"

Produce an output equal to Click "OK".

In [38]:
'Click "OK"' 

'Click "OK"'

Include a plus sign in your line of code to produce 'Big Houses'.

Include a trailing comma in your line of code to produce Big Houses.

Please note: The output you produce should consist of two lines of code, each of which generates the same result.

In [41]:
print('Big' + ' Houses')

Big Houses


In [42]:
print('Big' , ' Houses')

Big  Houses


# Python syntax fundamentals

Combine 15 and 23.

In [43]:
15+23

38

Subtract 50 from 26.

In [44]:
50-26

24

Divide 20 by 4.

In [46]:
20/4

5.0

In [47]:
22/4

5.5

Obtain the remainder of the division of 22 by 4.

In [48]:
22%4

2

Divide the float 22 by 4.

In [49]:
float(22)/4

5.5

Multiply 6 by 8.

In [51]:
6*8

48

Raise 15 to the power of 2.

In [52]:
15**2

225

Demonstrate that 100 is not equal to 98.

In [53]:
100==98

False

Assign the value of 14 to a variable p.

In [54]:
p=14

Calculate p + 10.

In [56]:
p+10

24

assign 30 to variable p

In [58]:
p=30

In [59]:
p+10

40

In [62]:
15 + 31 \
- 26

20

Extract the letter 'B' from "Bingo!".

In [63]:
"Bingo!"[0]

'B'

Extract the letter "u" from "Constitution".

In [64]:
"Constitution"[7]

'u'

Use indentation properly to print the result of a function called ten() which can be called with any value for the argument x.

In [74]:
def ten(x):
    x=10
    return x
print (ten(10))

10


 # Python operators

Verify that 25 is smaller than 30.

In [76]:
25<30

True

Verify that 5 multiplied by 3 is less than or equal to 5 to the power of 3.

In [77]:
5/3 <= 5**3

True

Verify that 100 is equal to 10 square.

In [80]:
100 == 10**2

True

In [ ]:
Verify that 53 is not equal to 46.

In [81]:
53 !=46

True

In [82]:
False or not True and not False

False

In [83]:
True and not False and True or not False

True

In [84]:
True or False and False

True

In [85]:
False and True or False

False

Using an identity operator, verify that 10 is not the same as 12.

In [92]:
10 is not 12

<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
C:\Users\Yoga\AppData\Local\Temp\ipykernel_18504\2742155778.py:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  10 is not 12


True

In [93]:
 50 is 50

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Yoga\AppData\Local\Temp\ipykernel_18504\3061638254.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  50 is 50


True

# Conditional Statements

Create a two-line code that prints "The condition has been satisfied" if 5 is greater than 2.



In [94]:
if 5>2:
    print("The condition has been satisfied")

The condition has been satisfied


Assign 10 to the variable x and 25 to the variable y. In the same cell, create 2 conditional statements. Let the first one print "Both conditions are correct" if x is greater then 3 and y is greater than 13. Let the second one print "At least one of the conditions is false" if x is less than or equal to 3 or y is less than or equal to 13. Change the values assigned to x and y and re-run the cell to verify your code still works.


In [100]:
x=10
y=25
if x>3 and y>13:
    print("Both conditions are correct")

Both conditions are correct


In [101]:
x=1
y=25
if x<=3 or y<=13:
    print("At least one of the conditions is false")

At least one of the conditions is false


Let x represent the number of orders received during a certain day. Create a program that prints "A busy day" if x is greater than 100, and "A calm day" otherwise.

In [103]:
x=200
if x>100:
    print("A busy day")
else:
    print("A calm day")

A busy day


Create the following piece of code: If x > 200, print out "Big"; If x > 100 and x <= 200, print out "Average"; and If x <= 100, print out "Small". Use the if, elif, and else keywords in your code.

In [111]:
def comparison(x):
    if x>200:
        print("Big")
    elif x<=200 and x>100:
        print("Average")
    elif x<=100:
        print("Small")
        

In [112]:
comparison(5)

Small


Keep the first two conditions of the code from the previous exercise (if x > 200, print out "Big"; If x > 100 and x <= 200, print out "Average").

Add a new elif statement, so that, eventually, the program prints "Small" if x >= 0 and x <= 100, and "Negative" if x < 0.

In [113]:
x = 0

if x > 200: 
    print ("Big")
elif x > 100 and x <= 200:
    print ("Average")
elif x >= 0 and x <= 100:
    print("Small")
elif x<0:
    print ("Negative")

Small


# Functions

Define a function called multiplication_by_2(x) that returns a value equal to its argument multiplied by 2.

In [121]:
def multiplication_by_2(x):
    return (x*2)

In [122]:
multiplication_by_2(10)

20

Define a function called division_by_2(x) that returns a float value equal to its argument divided by 2.

In [119]:
def division_by_2(x):
    return(float(x)/2)

In [120]:
division_by_2(9)

4.5

Define a function called exponentiation_exp_2(x) that states the value of the argument accompanied by the phrase "Raised to the power of 2:" and returns a value equal to its argument raised to the power of 2. This time, use a new variable, called result, in the body of the Function. Call the function with some argument to verify it works properly.



In [133]:
def exponentiation_exp_2(x):
    print("Raised to the power of 2:")
    return x**2

In [134]:
exponentiation_exp_2(5)

Raised to the power of 2:


25

Define a function called plus_five() that adds 5 to its argument. Then, define another function named m_by_3() that multiplies the argument (the result obtained from plus_five()) by 3. Verify your code was correct by calling the second function with an argument of 5. Was your output equal to 30?


In [137]:
def plus_five(x):
    return x+5
def m_by_3():
    return plus_five(x) *3

In [140]:
plus_five(3), m_by_3()

(8, 15)

Define a function, called compare_the_two(), with two arguments. If the first one is greater than the second one, let it print "Greater". If the second one is greater, it should print "Less". Let it print "Equal" if the two values are the same number.

In [141]:
def compare_the_two(x,y):
    if x>y:
        return "Greater"
    elif x<y:
        return "Less"
    elif x==y:
        return "Equal"

In [144]:
compare_the_two(2,4)

'Less'

Obtain the maximum number among the values 25, 65, 890, and 15.

In [145]:
max(25,65,890,15)

890

Obtain the minimum number among the values 25, 65, 890, and 15.

In [148]:
min(25, 65, 890,15)

15

Find the absolute value of -100.


In [151]:
abs(-100)

100

Round the value of 55.5.


In [159]:
round(55.5)

56

Round 35.56789 to the third digit.

In [160]:
round(35.56789,3)

35.568

In [161]:
Numbers = [1, 5, 64, 24.5]
sum(Numbers)

94.5

Use a built-in function to raise 10 to the power of 3.

In [162]:
pow(10,3)

1000

In one line of code, find how many characters there are in the word "Elephant"?

In [166]:
len("Elephant")

8

Create a function, called distance_from_zero(), that returns the absolute value of a provided single argument and prints a statement "Not possible" if the argument provided is not a number. To solve the task, use the type() function in the body of distance_from_zero().

Call the function with the values of -10 and "cat" to verify it works correctly.

In [187]:
def distance_from_zero(x):
    if isinstance(x, (int, float)):
        return abs(x)
    else:
        return "Not possible"

In [188]:
distance_from_zero(-10)

10

In [189]:
distance_from_zero('cat')

'Not possible'

Create a list, called Numbers. Let it contain the numbers 10, 25, 40, and 50.

Print the element at index 2 from the list.

# Python Sequences

In [1]:
Numbers =[10,25,40,50]
print(Numbers[2])

40


Append the number 100 to the Numbers list.

In [2]:
Numbers = [15, 40, 50]
Numbers.append(100)

In [3]:
Numbers

[15, 40, 50, 100]

With the help of the .extend() method, add the numbers 115 an 140 to the Numbers list.


In [4]:
Numbers = [15, 40, 50, 100]
Numbers.extend([155,140])

Print a statement, saying "The fourth element of the Numbers list is" followed by the value of the fourth element of the Numbers list. Ensure you use a trailing comma to concatenate the statement with the value.

In [8]:
Numbers = [15, 40, 50, 100, 115, 140]
print("The fourth element of the Numbers list is" , Numbers[4] , '.' )

The fourth element of the Numbers list is 115 .


In [9]:
len(Numbers)

6

Using list slicing, obtain the numbers 100 and 115.

In [11]:
Numbers = [15, 40, 50, 100, 115, 140]
Numbers[3:5]

[100, 115]

In [ ]:
Using slicing, extract the first four elements from the list.

In [13]:
Numbers = [15, 40, 50, 100, 115, 140]
Numbers[:4]

[15, 40, 50, 100]

Using slicing, extract all the elements from the list from the 3rd position onwards.

In [15]:
Numbers = [15, 40, 50, 100, 115, 140]
Numbers[3:]

[100, 115, 140]

In [ ]:
Using slicing, extract the last 4 elements from the list.

In [17]:
Numbers = [15, 40, 50, 100, 115, 140]
Numbers[-4:]

[50, 100, 115, 140]

Which is the position of the value 15?

In [20]:
Numbers = [15, 40, 50, 100, 115, 140]
Numbers.index(15)

0

Create a list, called Two_Numbers. Let its elements be the values 1 and 2. Then, create a new one, named All_Numbers, that will contain both the Two_Numbers and the Numbers lists in the given order.



In [23]:
Numbers = [15, 40, 50, 100, 115, 140]
Two_Numbers = [1,2]
All_Numbers= [Two_Numbers,Numbers]
All_Numbers

[[1, 2], [15, 40, 50, 100, 115, 140]]

Sort all the numbers in the Numbers list from the largest to the smallest.

In [32]:
Numbers = [15, 40, 50, 100, 115, 140]
Numbers.sort(reverse=True)
Numbers

[140, 115, 100, 50, 40, 15]

Create a tuple, called Cars, with elements "BMW", "Dodge", and "Ford" in the given order.



In [34]:
Cars = ("BMW", "Dodge", "Ford")
Cars[1]

'Dodge'

Call a method that would allow you to extract the provided name and age separately. Then print the name and age values to see if you worked correctly.


In [36]:
name, age = 'Peter,24'.split(',')

Create a function called rectangle_info() that takes the length and width of a rectangle as arguments. The function should then return the area and the perimeter of the rectangle. Call the function with arguments 2 and 10 to verify it worked correctly.



In [1]:
def rectangle_info(l,w):
    print( "Area =" , l*w)
    return ("parameter = " , l+w)

In [2]:
rectangle_info(2,10)

Area = 20


('parameter = ', 12)

In [3]:
rectangle_info(2,1)

Area = 2


('parameter = ', 3)

In [4]:
rectangle_info(2,4)

Area = 8


('parameter = ', 6)

# Using Iterations